services:
  - type: web
    name: tds-project-api
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: USER_SECRET
        sync: false
      - key: OPENAI_BASE_URL
        value: https://aipipe.org/openai/v1